#!/bin/sh -eu

if ! git config --get --local user.name; then
  echo "error: user.name is not set in git config"
  exit 1
fi
if ! git config --get --local user.email; then
  echo "error: user.email is not set in git config"
  exit 1
fi
